# Generated by Django 4.2.7 on 2024-01-11 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devmates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devmate',
            name='created_at',
        ),
    ]
