# Generated by Django 4.2.7 on 2024-01-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='development_field',
            field=models.CharField(choices=[('FE', '프론트엔드'), ('BE', '백엔드'), ('DBA', '데이터베이스')], max_length=100),
        ),
    ]
