# Generated by Django 4.2.7 on 2024-03-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_auth_code_user_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', '이메일'), ('github', 'GitHub')], default='email', max_length=100),
        ),
    ]
