# Generated by Django 4.2.7 on 2024-01-10 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('alert_set', models.CharField(choices=[('없음', '없음'), ('1시간', '1시간'), ('6시간', '6시간'), ('하루 전', '하루 전')], max_length=20, null=True)),
                ('status', models.IntegerField()),
                ('study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='studies.study')),
            ],
            options={
                'verbose_name': '할 일',
                'verbose_name_plural': '할 일',
            },
        ),
        migrations.CreateModel(
            name='ToDoAssignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_assignees', to=settings.AUTH_USER_MODEL)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_assignees', to='todos.todo')),
            ],
            options={
                'verbose_name': '할 일 담당자',
                'verbose_name_plural': '할 일 담당자',
            },
        ),
    ]
