# Generated by Django 4.2.7 on 2024-01-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-id'], 'verbose_name': '할 일', 'verbose_name_plural': '할 일'},
        ),
        migrations.AlterField(
            model_name='todo',
            name='alert_set',
            field=models.CharField(choices=[('없음', '없음'), ('1시간', '1시간'), ('6시간', '6시간'), ('하루 전', '하루 전')], default='없음', max_length=20),
        ),
        migrations.AlterField(
            model_name='todo',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('ToDo', 'ToDo'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='ToDo', max_length=20),
        ),
    ]
