# Generated by Django 4.2.7 on 2024-01-25 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todo_options_alter_todo_alert_set_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': '할 일', 'verbose_name_plural': '할 일'},
        ),
    ]
