# Generated by Django 4.2.7 on 2024-01-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='thumbnail',
            field=models.ImageField(blank=True, default='./static/thumbnail_default/thumbnail_default.png', null=True, upload_to='study/imgs/%Y/%m/%d/'),
        ),
    ]
