# Generated by Django 4.2.7 on 2024-01-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_alter_study_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='topic',
        ),
        migrations.AddField(
            model_name='study',
            name='tag',
            field=models.ManyToManyField(related_name='studies', to='studies.tag'),
        ),
        migrations.AddField(
            model_name='study',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='tag',
            name='study',
        ),
        migrations.AddField(
            model_name='tag',
            name='study',
            field=models.ManyToManyField(related_name='tags', to='studies.study'),
        ),
    ]
