# Generated by Django 4.2.7 on 2024-01-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_alter_study_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='topic',
        ),
        migrations.AddField(
            model_name='study',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
