# Generated by Django 4.2.7 on 2024-02-19 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0005_remove_study_topic_study_tag_study_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflink',
            name='study',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_links', to='studies.study'),
        ),
    ]
