# Generated by Django 4.2.7 on 2024-02-19 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0006_alter_reflink_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflink',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_links', to='studies.study'),
        ),
    ]
