# Generated by Django 4.2.7 on 2024-02-26 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0007_alter_reflink_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='current_member',
        ),
    ]
