# Generated by Django 4.2.7 on 2024-03-11 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0008_remove_study_current_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='study',
        ),
    ]
