# Generated by Django 4.2.7 on 2024-03-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0009_remove_tag_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='studies', to='studies.tag'),
        ),
    ]
