# Generated by Django 4.2.7 on 2024-03-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0010_alter_study_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default/study_thumbnail.png', null=True, upload_to='study/imgs/%Y/%m/%d/'),
        ),
    ]
