# Generated by Django 4.2.7 on 2024-03-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0011_alter_study_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='study/imgs/%Y/%m/%d/'),
        ),
    ]
