name: DeVtail CI/CD

env:
  GITHUB_CLIENT_ID: CLIENT_GITHUB_ID
  GITHUB_CLIENT_SECRET: CLIENT_GITHUB_SECRET
  GITHUB_REDIRECT_URI: REDIRECT_GITHUB_URI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 체크아웃 레포지토리
      uses: actions/checkout@v3
      
    - name: 파이썬 설정
      id: setup-py
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: 의존성 캐싱
      id: cache-venv
      uses: actions/cache@v3
      with:
        path: ./.venv
        key: ${{ runner.os }}-${{ steps.setup-py.outputs.python-version }}-venv-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-${{ steps.setup-py.outputs.python-version }}-venv-
        
    - name: 의존성 설치
      if: steps.cache-venv.outputs.cache-hit != 'true'
      shell: bash
      run: |
        python -m venv ./.venv
        source ./.venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Tests
      shell: bash
      run: |
        source ./.venv/bin/activate
        python manage.py test
      env :
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: ${{ secrets.DEBUG }}

    - name: 서버 배포
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          set -e
          cd /home/ubuntu/DeVtail
          git pull origin main

          echo "SECRET_KEY=\"${{ secrets.SECRET_KEY }}\"" > .env
          echo "DEBUG='${{ secrets.DEBUG }}'" >> .env
          echo "GITHUB_CLIENT_ID='${{ vars.CLIENT_GITHUB_ID }}'" >> .env
          echo "GITHUB_CLIENT_SECRET='${{ vars.CLIENT_GITHUB_SECRET }}'" >> .env
          echo "GITHUB_REDIRECT_URI='${{ vars.REDIRECT_GITHUB_URI }}'" >> .env

          source ../venv/bin/activate
          python manage.py makemigrations
          python manage.py migrate
          sudo systemctl restart devtail.service
